services:
  db:
    image: mariadb #database
    container_name: nextcloud_db
    restart: unless-stopped
    volumes:
      - ./mariadb/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=YOUR_PASSWORD
      - MYSQL_USER=YOUR_USER_NAME
      - MYSQL_PASSWORD=YOUR_USER_PASSWORD
      - MYSQL_DATABASE=nextcloud
    networks:
      - nextcloud_network

  adminer:
    image: adminer #database interface
    restart: unless-stopped
    ports:
      - 8000:8080
    networks:
      - nextcloud_network

  app:
    # image: nextcloud #nextcloud
    build: .
    container_name: nextcloud_app
    restart: unless-stopped
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - ./nextcloud/html:/var/www/html
      - ./nextcloud/custom_apps:/var/www/html/custom_apps
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data
      # - /media/wilson/wwilsonDoc:/mnt/wilsonDoc #extra storge
    environment:
      - NEXTCLOUD_ADMIN_USER=ADMIN_USER_NAME
      - NEXTCLOUD_ADMIN_PASSWORD=ADMIN_USER_PASSWORD
      - MYSQL_USER=YOUR_USER_NAME
      - MYSQL_PASSWORD=YOUR_USER_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_HOST=db
    networks:
      - nextcloud_network
      
  # nginx:
  #   image: nginx #web server
  #   container_name: nextcloud_nginx
  #   restart: unless-stopped
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./nextcloud/html:/var/www/html
  #   networks:
  #     - nextcloud_network

  cloudflared:
    image: cloudflare/cloudflared #cloudflare tunnel
    container_name: cloudflared_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=YOUR_TOKEN 
    networks:
      - nextcloud_network

networks:
  nextcloud_network:
    name: nextcloud_network
    driver: bridge